### ISSUE TITLE
Thank you for this great and comprehensive example

### ISSUE THREAD

**Issue by benjaminrau** [martin-helmich/flow-restapi-example#1]
Hi Martin.

Excuse me that i use the issues but i wanted to send you my thanks.

I didnt implement a REST api before and on my research i stumpled over your implementation and example. Thanks for making it such comprehensive!

If you try something for the first time its hard to design the pattern on its own but a lot easier an more reasonable to understand when having the chance to learn from a already implemented pattern.

Since friday morning i didnt get a lot of sleep but i can say - this REST api ive implemented now is better than and more satisfying than every api ive done before :)

Thank you so much for your work! Keep it up.

Cheers Ben

PS: Sorry for this.. i just wanted to let you know about it ;)

**Comment by martin-helmich** [comment]
Happy to help, and thanks for your encouraging feedback!
